apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-weather
  labels:
    app: example-weather
spec:
  selector:
    matchLabels:
      app: example-weather
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-weather
    spec:
      containers:
      - name: example-weather
        image: 292627/weather:miniapp1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"